baseURL = 'https://distribits.live'
languageCode = 'en-us'
title = 'distribits'
theme = "PaperMod2"

# see https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

[menu]
  [[menu.main]]
    name = "News"
    url = "news/"
    weight = 5
    
[params]
  [params.profileMode]
    enabled = true
    title = 'Technologies for distributed data management'
    # subtitle = "Supported by DataLad and git-annex"
    imageUrl = "pics/distribits_logo_a.svg"
    imageTitle = "distribits_logo"
    imageWidth = 800
#  [[params.profileMode.buttons]]
#    name = "🚀 Register"
#    url = 'https://cryptpad.fr/form/#/2/form/view/jnreOeG+ja0DXCESlqkgf6WRqz7vhMmxzROMyJL+q5g/'

  # repeat as many times as needed
  # icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
  [[params.socialIcons]]
    name = "mastodon"
    url = "https://fosstodon.org/@distribits"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/distribits"
